version: '3.8'

services:
  db:
    image: postgres
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - database:/var/lib/postgresql/data/
    env_file:
      - ./.env

volumes:
  database:
